def AreaEntrance():
    print ('~There is thunder in the sky. \nThe skies darken.~')
    print (f' {Pip}: {PlayerName}, This darkness!! It seems to be approaching us from the Sky!!!!')
    print ('~The earth starts to shake and you cannot see anything as it is now pitch black. \nYou hear a voice in your head.~')

AreaEntrance

class Spirits:

    def MountainSpirit():
        print ('Unknown Voice: IT SEEMS YOU ARE THE HERO THE TOWN OF OUTPUT HAS SENT TO SAVE THEM. \nI AM THE SPIRIT OF THE MOUNTAINS AND I WILL GRANT YOU POWER OF STRENGTH, MAGIC, ENDURANCE, AND SPEED. \nBECAUSE YOU HAVE ENTERED THE MOUNTAINS I CAN GRANT YOU SLIGHTLY MORE POWER FOR STRENGTH AND HEALTH. \nREMEMBER, YOU CAN UPGRADE THESE ABILITIES AS YOU PROGRESS THROUGH YOUR ADVENTURE BUT YOU ARE STILL MORTAL AND THE GREAT EVIL CAN STILL DESTROY YOU. PROCEED WITH CAUTION. \nI BELIEVE IN YOU.....')
        print ('~The darkness fades and you are left with a new sense of power.~')

    def WoodsSpirit():
        print ('Unknown Voice: IT SEEMS YOU ARE THE HERO THE TOWN OF OUTPUT HAS SENT TO SAVE THEM. \nI AM THE SPIRIT OF THE WOODS AND I WILL GRANT YOU POWER OF STRENGTH, MAGIC, ENDURANCE, AND SPEED. \nBECAUSE YOU HAVE ENTERED THE WOODS I CAN GRANT YOU SLIGHTLY MORE POWER FOR MAGIC AND HEALTH. \nREMEMBER, YOU CAN UPGRADE THESE ABILITIES AS YOU PROGRESS THROUGH YOUR ADVENTURE BUT YOU ARE STILL MORTAL AND THE GREAT EVIL CAN STILL DESTROY YOU. PROCEED WITH CAUTION. \nI BELIEVE IN YOU.....')
        print ('~The darkness fades and you are left with a new sense of power.~')
        
    def SeaSpirit():
        print ('Unknown Voice: IT SEEMS YOU ARE THE HERO THE TOWN OF OUTPUT HAS SENT TO SAVE THEM. \nI AM THE SPIRIT OF THE SEA AND I WILL GRANT YOU POWER OF STRENGTH, MAGIC, ENDURANCE, AND SPEED. \nBECAUSE YOU HAVE ENTERED THE SEA I CAN GRANT YOU SLIGHTLY MORE POWER FOR ENDURANCE AND HEALTH. \nREMEMBER, YOU CAN UPGRADE THESE ABILITIES AS YOU PROGRESS THROUGH YOUR ADVENTURE BUT YOU ARE STILL MORTAL AND THE GREAT EVIL CAN STILL DESTROY YOU. PROCEED WITH CAUTION. \nI BELIEVE IN YOU.....')
        print ('~The darkness fades and you are left with a new sense of power.~')